# Generated by Django 3.2.15 on 2022-10-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Marka', models.CharField(max_length=200, null=True)),
                ('ModelAdi', models.CharField(max_length=200, null=True)),
                ('Modelno', models.CharField(max_length=200, null=True)),
                ('İşletimSistemi', models.CharField(max_length=200, null=True)),
                ('İslemciTipi', models.CharField(max_length=200, null=True)),
                ('İslemciNesli', models.CharField(max_length=200, null=True)),
                ('Ram', models.CharField(max_length=200, null=True)),
                ('DiskBoyutu', models.CharField(max_length=200, null=True)),
                ('DiskTürü', models.CharField(max_length=200, null=True)),
                ('EkranBoyutu', models.CharField(max_length=200, null=True)),
                ('Puanı', models.CharField(max_length=200, null=True)),
                ('Fiyat', models.CharField(max_length=200, null=True)),
                ('Siteİsmi', models.CharField(max_length=200, null=True)),
                ('SiteLinki', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
